# Generated by Django 3.1.7 on 2021-03-30 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('align', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SiteBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.content')),
            ],
        ),
        migrations.CreateModel(
            name='SurprizePassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_type', models.CharField(choices=[('text', 'Любой текст'), ('date', 'Памятная дата'), ('name', 'Имя человека')], max_length=4)),
                ('password', models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name='GetSurprizeContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creator.content')),
                ('link', models.CharField(max_length=1024)),
            ],
            bases=('creator.content',),
        ),
        migrations.CreateModel(
            name='ImageContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creator.content')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=124)),
            ],
            bases=('creator.content',),
        ),
        migrations.CreateModel(
            name='MusicContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creator.content')),
                ('music', models.FileField(upload_to='')),
            ],
            bases=('creator.content',),
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='creator.content')),
                ('text', models.TextField()),
            ],
            bases=('creator.content',),
        ),
        migrations.CreateModel(
            name='SurprizeLanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=124)),
                ('birthday_full_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('blocks', models.ManyToManyField(to='creator.SiteBlock')),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.surprizepassword')),
            ],
        ),
    ]
