# Generated by Django 3.1.7 on 2021-03-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20210330_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteblock',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
